language: cpp

compiler:
    - gcc
    - clang

env:
  global:
    - PREFIX=$(mktemp -d /tmp/mongo-cxx-driver-install.XXXXXX || exit 1)
    - COVERALLS_OPTS="--exclude=src/third_party"

# Setup required repositories before installation
before_install:
    - sudo add-apt-repository -y ppa:jkeiren/ppa
    - sudo apt-get update -qq

install:
    # Install Boost 1.49 dependencies via PPA
    - sudo apt-get install -qq
      libboost1.49-dev
      libboost-program-options1.49-dev
      libboost-filesystem1.49-dev
      libboost-thread1.49-dev
    # Install coveralls for code coverage
    - sudo pip install cpp-coveralls --use-mirrors

script:
    - scons
       -j2
       --prefix=$PREFIX
       --ssl
       --use-sasl-client
       --dbg=on
       --gcov
       unittests
    - scons
      --prefix=$PREFIX
      --ssl
      --use-sasl-client
      --dbg=on
      --gcov
      test

after_success:
    # Send coverage data to coveralls
    - coveralls ${COVERALLS_OPTS}

