language: cpp

compiler:
    - gcc
    - clang

env:
  global:
    - PREFIX=$(mktemp -d /tmp/mongo-cxx-driver-install.XXXXXX || exit 1)
    - COMMON_FLAGS="--mute --prefix=${PREFIX} --use-system-boost --full --sharedclient --ssl --use-sasl-client --dbg=on"

# Setup required repositories before installation
before_install:
    - sudo add-apt-repository -y ppa:jkeiren/ppa
    - sudo apt-get update -qq

# Install Boost 1.49 dependencies via PPA
install:
    - sudo apt-get install -qq
        libboost1.49-dev
        libboost-program-options1.49-dev
        libboost-filesystem1.49-dev
        libboost-thread1.49-dev

script:
    # Build all targets under current directory and install
    # TODO: use all target here when fixed
    - scons
        ${COMMON_FLAGS}
        .
        install-mongoclient

    # Run unit tests and verify header installation
    # TODO: run smokeClient -- with mongod on 27999
    - scons
        ${COMMON_FLAGS}
        test
        check-install-mongoclient
